### ISSUE TITLE
문 선택 및 입력받기

### ISSUE THREAD

**Issue by hyogg** [yeardream-17/17#1]
## Description
1. 3개의 문 중에서 정답 문을 무작위로 선택합니다.
2. 참가자가 선택한 문을 입력받습니다.

## Tasks
- [ ] Random
- [ ] input 받기

## Reference

**Comment by jeongjae96** [comment]
화이팅!

**Comment by hyogg** [comment]
> 화이팅!

감사합니다 팀장님!
