### ISSUE TITLE
정답이 아닌 문과 나머지 문 선택 기능을 구현

### ISSUE THREAD

**Issue by kang952175** [yeardream-17/17#2]
## Description
몬티 홀 문제에서 참가자가 선택한 문과 정답이 아닌 다른 문을 선택하는 기능과 참가자가 선택한 문과 정답이 아닌 다른 문을 제외한 나머지 문을 선택하는 기능을 구현해보겠습니다.

## Tasks

- [ ] 기능1. 참가자가 선택한 문과 정답이 아닌 다른 문을 선택하는 기능입니다.
- [ ] 기능2. 참가자가 선택한 문과 정답이 아닌 다른 문을 제외한 나머지 문을 선택하는 기능입니다.

**Comment by jeongjae96** [comment]
화이팅!!

**Comment by hyogg** [comment]
세부적으로 적으셨네요 많이 배우겠습니다.

**Comment by SohyeonGyeong** [comment]
정석이라고 소문듣고 왔습니다. 잘 설명해주셨네요! 감사합니다
