### ISSUE TITLE
문 바꿀지 물어봅시다!

### ISSUE THREAD

**Issue by PY-An** [yeardream-17/17#5]
## Description
참가자에게 다른 문으로 바꿀 것인지 물어봅니다.

## Tasks
- [x] change door?
- [x] y 를 반환합니다.

**Comment by hyogg** [comment]
yyyy가 무엇인가요?

**Comment by jeongjae96** [comment]
yyyyy

**Comment by PY-An** [comment]
> yyyy가 무엇인가요?

change door 의 return 입니담
