### ISSUE TITLE
몬티 홀 게임을 실행하는 코드를 작성했습니다.

### ISSUE THREAD

**Issue by SohyeonGyeong** [yeardream-17/17#6]
## Description
효정님과 필용님, 도성님이 만들어주신 함수와 기능들을 불러와서 
게임을 실행합니다. 

## Tasks

- [ ] 기능1 게임설명과 안내를 출력해줍니다.
- [ ] 기능2 게임을 끝내기도 합니다.🥲

## Reference
도성님이 보내주신 파이썬 코드 참고했습니다.

**Comment by jeongjae96** [comment]
세세하게 잘 적어주셨네요! Good
